### PR TITLE
Feat/POAP setting

### PR DESCRIPTION
**Pull request by HabacucMX**

### CODE REVIEW

**Comment by HabacucMX** [comment]
TODOs:
- [ ] Fetch POAP images from POAP API (currently fetch from public/assets)
- [ ] Fetch POAP URL from POAP API (currently hardcoded to personal example)
- [ ] Verify reload after getting the POAP to display the result

**Comment by Markkos89** [comment]
> @Markkos89 TODOs:
> 
> * [ ]  Fetch POAP images from POAP API (currently fetch from public/assets)

If we fetch the poap nft just to get the image it is apropiate use the image from the public folder and avoid not mandatory requests...

> * [ ]  Fetch POAP URL from POAP API (currently hardcoded to personal example)

the `POAP URL` is this one: `https://app.poap.xyz/token/6741694` ? 

If so, the token claimed URL is obtained from one of the api calls working?

> * [ ]  Verify reload after getting the POAP to display the result

Noted. Define the onboarding (moderators) flow first would help a lot here, hence the issue relies on how the pages/components are built and being used.


@HabacucMX Let me know. Regards!

**Comment by HabacucMX** [comment]
> * [ ]   Fetch POAP URL from POAP API (currently hardcoded to personal example) 
> the `POAP URL` is this one: `https://app.poap.xyz/token/6741694` ?
> If so, the token claimed URL is obtained from one of the api calls working?

I understand that we will use the get `/token/{tokenId}` to fetch the the value and add it to the https prefix: 
`https://app.poap.xyz/token/{tokenID}`
https://documentation.poap.tech/reference/gettoken-2

**Comment by Markkos89** [comment]
> > * [ ]    Fetch POAP URL from POAP API (currently hardcoded to personal example)
> >   the `POAP URL` is this one: `https://app.poap.xyz/token/6741694` ?
> >   If so, the token claimed URL is obtained from one of the api calls working?
> 
> I understand that we will use the get `/token/{tokenId}` to fetch the the value and add it to the https prefix: `https://app.poap.xyz/token/{tokenID}` https://documentation.poap.tech/reference/gettoken-2

It makes no sense. fetch by tokenId to then add the tokenId to a url?

we have this functions to scan

image

perhaps the url or the token Id can be taken from there....

**Comment by HabacucMX** [comment]
It is a two-step process, first to fetch the `tokenId` with a get[ `/actions/scan/{address}/{eventId}`](https://documentation.poap.tech/reference/getactionsscan), and then to populate the `https://app.poap.xyz/token/{tokenID}` with the given `tokenID` value in the `Ver POAP` link from the the `OnboardingMods` and `OnboardingCitizens` components after the user mints the POAP:

```
<Link href="https://app.poap.xyz/token/{tokenID">
    Ver POAP
 </Link> 
```
Screenshot 2023-09-02 at 15 39 32

Screenshot 2023-09-02 at 15 42 33

I hope this helps make sense of how the process could work; otherwise, I would appreciate your help finding a way to do it properly.

**Review by Markkos89 — APPROVED** [review]

**Pull request merged**
